[package]
name = "gm_environ"
version = "0.2.2"
edition = "2021"

[lib]
name = "environ"
crate-type = ["cdylib"]

[features]
gmcl = []

[dependencies]
gmod = {version = "10.2.2", features = ["gmcl"], default-features = false}
debug_print = "1.0.0"
lazy_static = "1.4.0"
